### ISSUE TITLE
자동 검색 기능 구현

### ISSUE THREAD

**Issue by kooym5607** [kookmin-sw/capstone-2020-22#1]
- [x] 검색을 했을 때 연관된 검색어 띄우기

- [x] 검색어를 클릭할 시 그 장소의 위도,경도를 저장

- [x] 위젯사용이 아닌 커스텀한 검색창 구현

**Comment by kmj-audwls** [comment]
위젯 사용을 하지 않고 커스텀 검색창은 잘 안되고 있는중
